name: create-rc-thread
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'master'
permissions:
  id-token: write
  contents: read
jobs:
  create-rc-thread:
    uses: DispatchMe/github-actions/.github/workflows/create-rc-thread.yml@master
    secrets: inherit
